apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: parthlukhi/movie-app:v1.0
        ports:
        - containerPort: 8000
        env:
        - name: KUBECONFIG
          value: /Users/parthlukhi/Downloads/Go-Kubernetes/config/kubeconfig
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: /Users/parthlukhi/Downloads/Go-Kubernetes/config/kubeconfig
          subPath: kubeconfig
      volumes:
      - name: kubeconfig-volume
        configMap:
          name: kubeconfig