apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: kubectl describe nodes <node-name>
        certificate-authority-data: your-cluster-ca-cert-base64  # Optional, if your cluster uses TLS
      name: your-cluster
    contexts:
    - context:
        cluster: your-cluster
        namespace: default
      name: default-context
    current-context: default-context
    preferences: {}
    users: []
